apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    app: my-app
spec:
  type: NodePort
  selector:
    environment: dev
  ports:
    - protocol: TCP
      port: 3000          # The port the service exposes
      targetPort: 3000    # The port the container listens on
      nodePort: 31000    # The port on the Node where the service is accessible (optional, auto-assigned if omitted)
